ARQ_CHAVE = "K_{chave}_{numero}.bin"
ARQ_CONJ  = "C_{tamanho}_{base}.json"
ARQ_BASE  = "{modo}_{tipo}_{base}_{chave}_[V{sub}_{ambiente}].bin"

ARQ_EXP_CSV   = "[{estado}]EXP_{topologia}_{computador}.csv"
ARQ_EXP_JSON  = "[{estado}]EXP_{topologia}_{computador}.json"
ARQ_EXP_COMUM = "[{estado}]EXP_{topologia}_{computador}.{formato}"
ARQ_NOME_DATA = "{ano}-{mes}-{dia}.bin"
ARQ_CONJUNTOS = "Conjuntos_totais.json"
ARQ_DATASET   = "Datasets.json"